deps_config := \
	/home/intel_2/zephyr-project/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.stm32f103rb \
	/home/intel_2/zephyr-project/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.stm32f103ve \
	/home/intel_2/zephyr-project/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.series \
	/home/intel_2/zephyr-project/arch/arm/soc/nxp_kinetis/k6x/Kconfig.defconfig.mk64f12 \
	/home/intel_2/zephyr-project/arch/arm/soc/nxp_kinetis/k6x/Kconfig.defconfig.series \
	/home/intel_2/zephyr-project/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.defconfig.nrf52832 \
	/home/intel_2/zephyr-project/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.defconfig.series \
	/home/intel_2/zephyr-project/arch/arc/soc/em11d/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/arc/soc/em9d/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/arc/soc/quark_se_ss/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/arm/soc/atmel_sam3/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/arm/soc/nordic_nrf5/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/arm/soc/nxp_kinetis/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/arm/soc/st_stm32/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/arm/soc/ti_lm3s6965/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/nios2/soc/nios2e-zephyr/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/x86/soc/atom/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/x86/soc/ia32/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/x86/soc/quark_d2000/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/x86/soc/quark_se/Kconfig.defconfig \
	/home/intel_2/zephyr-project/arch/x86/soc/quark_x1000/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/altera_max10/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/arduino_101/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/arduino_101_sss/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/arduino_due/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/basic_cortex_m3/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/basic_minuteia/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/em_starterkit/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/frdm_k64f/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/galileo/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/minnowboard/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/nrf52_pca10040/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/nucleo_f103rb/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/olimexino_stm32/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/qemu_cortex_m3/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/qemu_x86/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/quark_d2000_crb/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/quark_se_devboard/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/quark_se_sss_devboard/Kconfig.defconfig \
	/home/intel_2/zephyr-project/boards/stm32_mini_a15/Kconfig.defconfig \
	/home/intel_2/zephyr-project/ext/lib/upm/Kconfig \
	/home/intel_2/zephyr-project/ext/lib/mraa/Kconfig \
	/home/intel_2/zephyr-project/ext/lib/crypto/tinycrypt/Kconfig \
	/home/intel_2/zephyr-project/ext/lib/crypto/Kconfig \
	/home/intel_2/zephyr-project/ext/hal/qmsi/Kconfig \
	/home/intel_2/zephyr-project/ext/hal/nordic/mdk/Kconfig \
	/home/intel_2/zephyr-project/ext/hal/cmsis/Kconfig \
	/home/intel_2/zephyr-project/ext/hal/Kconfig \
	/home/intel_2/zephyr-project/ext/Kconfig \
	/home/intel_2/zephyr-project/lib/Kconfig \
	/home/intel_2/zephyr-project/misc/debug/Kconfig \
	/home/intel_2/zephyr-project/misc/Kconfig \
	/home/intel_2/zephyr-project/net/ip/Kconfig.debug \
	/home/intel_2/zephyr-project/net/ip/Kconfig \
	/home/intel_2/zephyr-project/net/bluetooth/Kconfig \
	/home/intel_2/zephyr-project/net/Kconfig \
	/home/intel_2/zephyr-project/drivers/counter/Kconfig \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.tmp007 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.sx9500 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.sht3xd \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.mpu6050 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.mcp9808 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.lsm9ds0_mfd \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.lsm9ds0_gyro \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.lsm6ds0 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.lis3mdl \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.lis3dh \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.isl29035 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.hts221 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.hdc1008 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.dht \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.bmi160 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.bmg160 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.bme280 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.bmc150_magn \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.bma280 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig.ak8975 \
	/home/intel_2/zephyr-project/drivers/sensor/Kconfig \
	/home/intel_2/zephyr-project/drivers/flash/Kconfig \
	/home/intel_2/zephyr-project/drivers/aio/Kconfig \
	/home/intel_2/zephyr-project/drivers/ipm/Kconfig \
	/home/intel_2/zephyr-project/drivers/clock_control/Kconfig.stm32f10x \
	/home/intel_2/zephyr-project/drivers/clock_control/Kconfig.quark_se \
	/home/intel_2/zephyr-project/drivers/clock_control/Kconfig \
	/home/intel_2/zephyr-project/drivers/watchdog/Kconfig.stm32 \
	/home/intel_2/zephyr-project/drivers/watchdog/Kconfig \
	/home/intel_2/zephyr-project/drivers/rtc/Kconfig \
	/home/intel_2/zephyr-project/drivers/adc/Kconfig \
	/home/intel_2/zephyr-project/drivers/pinmux/Kconfig.stm32 \
	/home/intel_2/zephyr-project/drivers/pinmux/Kconfig.k64 \
	/home/intel_2/zephyr-project/drivers/pinmux/dev/Kconfig \
	/home/intel_2/zephyr-project/drivers/pinmux/Kconfig \
	/home/intel_2/zephyr-project/drivers/pwm/Kconfig.k64 \
	/home/intel_2/zephyr-project/drivers/pwm/Kconfig.dw \
	/home/intel_2/zephyr-project/drivers/pwm/Kconfig.qmsi \
	/home/intel_2/zephyr-project/drivers/pwm/Kconfig.pca9685 \
	/home/intel_2/zephyr-project/drivers/pwm/Kconfig \
	/home/intel_2/zephyr-project/drivers/i2c/Kconfig \
	/home/intel_2/zephyr-project/drivers/spi/Kconfig.dw \
	/home/intel_2/zephyr-project/drivers/spi/Kconfig \
	/home/intel_2/zephyr-project/drivers/shared_irq/Kconfig \
	/home/intel_2/zephyr-project/drivers/gpio/Kconfig.nrf5 \
	/home/intel_2/zephyr-project/drivers/gpio/Kconfig.stm32 \
	/home/intel_2/zephyr-project/drivers/gpio/Kconfig.atmel_sam3 \
	/home/intel_2/zephyr-project/drivers/gpio/Kconfig.k64 \
	/home/intel_2/zephyr-project/drivers/gpio/Kconfig.sch \
	/home/intel_2/zephyr-project/drivers/gpio/Kconfig.qmsi_ss \
	/home/intel_2/zephyr-project/drivers/gpio/Kconfig.qmsi \
	/home/intel_2/zephyr-project/drivers/gpio/Kconfig.mmio \
	/home/intel_2/zephyr-project/drivers/gpio/Kconfig.pcal9535a \
	/home/intel_2/zephyr-project/drivers/gpio/Kconfig.dw \
	/home/intel_2/zephyr-project/drivers/gpio/Kconfig \
	/home/intel_2/zephyr-project/drivers/pci/Kconfig \
	/home/intel_2/zephyr-project/drivers/grove/Kconfig \
	/home/intel_2/zephyr-project/drivers/random/Kconfig \
	/home/intel_2/zephyr-project/drivers/timer/Kconfig \
	/home/intel_2/zephyr-project/drivers/interrupt_controller/Kconfig.stm32 \
	/home/intel_2/zephyr-project/drivers/interrupt_controller/Kconfig \
	/home/intel_2/zephyr-project/drivers/serial/Kconfig.nrf5 \
	/home/intel_2/zephyr-project/drivers/serial/Kconfig.stm32 \
	/home/intel_2/zephyr-project/drivers/serial/Kconfig.qmsi \
	/home/intel_2/zephyr-project/drivers/serial/Kconfig.atmel_sam3 \
	/home/intel_2/zephyr-project/drivers/serial/Kconfig.nsim \
	/home/intel_2/zephyr-project/drivers/serial/Kconfig.stellaris \
	/home/intel_2/zephyr-project/drivers/serial/Kconfig.k20 \
	/home/intel_2/zephyr-project/drivers/serial/Kconfig.ns16550 \
	/home/intel_2/zephyr-project/drivers/serial/Kconfig \
	/home/intel_2/zephyr-project/drivers/ethernet/Kconfig \
	/home/intel_2/zephyr-project/drivers/console/Kconfig \
	/home/intel_2/zephyr-project/drivers/ieee802154/Kconfig \
	/home/intel_2/zephyr-project/drivers/bluetooth/nble/Kconfig \
	/home/intel_2/zephyr-project/drivers/bluetooth/Kconfig \
	/home/intel_2/zephyr-project/drivers/Kconfig \
	/home/intel_2/zephyr-project/kernel/microkernel/Kconfig \
	/home/intel_2/zephyr-project/kernel/nanokernel/Kconfig \
	/home/intel_2/zephyr-project/kernel/Kconfig \
	/home/intel_2/zephyr-project/boards/galileo/Kconfig \
	/home/intel_2/zephyr-project/boards/nrf52_pca10040/Kconfig \
	/home/intel_2/zephyr-project/boards/altera_max10/Kconfig.board \
	/home/intel_2/zephyr-project/boards/arduino_101/Kconfig.board \
	/home/intel_2/zephyr-project/boards/arduino_101_sss/Kconfig.board \
	/home/intel_2/zephyr-project/boards/arduino_due/Kconfig.board \
	/home/intel_2/zephyr-project/boards/basic_cortex_m3/Kconfig.board \
	/home/intel_2/zephyr-project/boards/basic_minuteia/Kconfig.board \
	/home/intel_2/zephyr-project/boards/em_starterkit/Kconfig.board \
	/home/intel_2/zephyr-project/boards/frdm_k64f/Kconfig.board \
	/home/intel_2/zephyr-project/boards/galileo/Kconfig.board \
	/home/intel_2/zephyr-project/boards/minnowboard/Kconfig.board \
	/home/intel_2/zephyr-project/boards/nrf52_pca10040/Kconfig.board \
	/home/intel_2/zephyr-project/boards/nucleo_f103rb/Kconfig.board \
	/home/intel_2/zephyr-project/boards/olimexino_stm32/Kconfig.board \
	/home/intel_2/zephyr-project/boards/qemu_cortex_m3/Kconfig.board \
	/home/intel_2/zephyr-project/boards/qemu_x86/Kconfig.board \
	/home/intel_2/zephyr-project/boards/quark_d2000_crb/Kconfig.board \
	/home/intel_2/zephyr-project/boards/quark_se_devboard/Kconfig.board \
	/home/intel_2/zephyr-project/boards/quark_se_sss_devboard/Kconfig.board \
	/home/intel_2/zephyr-project/boards/stm32_mini_a15/Kconfig.board \
	/home/intel_2/zephyr-project/boards/Kconfig \
	/home/intel_2/zephyr-project/arch/x86/soc/quark_se/Kconfig \
	/home/intel_2/zephyr-project/arch/x86/core/Kconfig \
	/home/intel_2/zephyr-project/arch/x86/soc/atom/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/x86/soc/ia32/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/x86/soc/quark_d2000/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/x86/soc/quark_se/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/x86/soc/quark_x1000/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/nios2/soc/nios2e-zephyr/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arm/soc/st_stm32/stm32f1/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arm/soc/nxp_kinetis/k6x/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arm/soc/atmel_sam3/Kconfig \
	/home/intel_2/zephyr-project/arch/arm/soc/nordic_nrf5/Kconfig \
	/home/intel_2/zephyr-project/arch/arm/soc/nxp_kinetis/Kconfig \
	/home/intel_2/zephyr-project/arch/arm/soc/st_stm32/Kconfig \
	/home/intel_2/zephyr-project/arch/arm/soc/ti_lm3s6965/Kconfig \
	/home/intel_2/zephyr-project/arch/arm/core/cortex_m/Kconfig \
	/home/intel_2/zephyr-project/arch/arm/core/Kconfig \
	/home/intel_2/zephyr-project/arch/arm/soc/st_stm32/stm32f1/Kconfig.series \
	/home/intel_2/zephyr-project/arch/arm/soc/nxp_kinetis/k6x/Kconfig.series \
	/home/intel_2/zephyr-project/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.series \
	/home/intel_2/zephyr-project/arch/arm/soc/atmel_sam3/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arm/soc/nordic_nrf5/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arm/soc/nxp_kinetis/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arm/soc/st_stm32/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arm/soc/ti_lm3s6965/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arc/soc/em11d/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arc/soc/em9d/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arc/soc/quark_se_ss/Kconfig.soc \
	/home/intel_2/zephyr-project/arch/arc/Kconfig \
	/home/intel_2/zephyr-project/arch/arm/Kconfig \
	/home/intel_2/zephyr-project/arch/nios2/Kconfig \
	/home/intel_2/zephyr-project/arch/x86/Kconfig \
	/home/intel_2/zephyr-project/arch/Kconfig \
	/home/intel_2/zephyr-project/Kconfig.zephyr \
	Kconfig

include/config/auto.conf: \
	$(deps_config)

ifneq "$(KERNELVERSION)" "1.4.0"
include/config/auto.conf: FORCE
endif

$(deps_config): ;
